### ISSUE TITLE
Reverse draw order for reverse view

### ISSUE THREAD

**Issue by psupine** [Myndale/Perfy#1]
This is such a tiny change I'm hoping Myndale can do this and I won't have to set up for C# development.

When showing the rear view, you could paint the blue vertical traces over the top of the red traces and perhaps use aqua rather than magenta a blu-ish colour for the overlapped pads.

It would just be an extra visual cue that we're looking at the reverse side

**Comment by Myndale** [comment]
Actually what it does at the moment is draw magenta where the two cross over irrespective of which side you're looking at, although at a casual glance it might look like it's always red. Thanks for the suggestion, I'll see if I can get some additional feedback on this one from other users.
