### ISSUE TITLE
Can not install on Windows 10

### ISSUE THREAD

**Issue by maded2** [Myndale/Perfy#2]
it keep saying security settings prevent the installer from running.  Any idea? as I already tried registry tick to lower the security.

thanks,
eddie

**Comment by Myndale** [comment]
Hi Eddie, I’ve just pushed [v1.0.0.4](https://github.com/Myndale/Perfy/blob/master/binaries/Perfy-1.0.0.4.zip) with what should be a fix for this. If you still have trouble try right-clicking and “Run as administrator”. If for some reason that still doesn’t work then let me know and I'll put up a standalone version.
