### ISSUE TITLE
Incorrect pad locations displayed on hover

### ISSUE THREAD

**Issue by johncblacker** [Myndale/Perfy#3]
When I hover my cursor over a pad, the program is displaying the alphabetic portion correctly but the numeric portion is high by 1.  So pad A1 displays as A,0.  You're apparently using numeric values relative to 0, instead of 1.  This makes for a confusing construction, to say the least.

**Comment by Myndale** [comment]
Can't believe that one's been sitting there all this time without anyone noticing. Fixed now, thanks for reporting it.
